# Create "installable" preview branches
#
# Commits to `main` push builds to a `preview` branch:
#   pnpm install "remix-run/remix#preview&path:packages/remix"
#
# Pull Requests create `preview/{number}` branches:
#   pnpm install "remix-run/remix#preview/12345&path:packages/remix"
#
# Can also be dispatched manually with base/installable branches to provide
# `experimental` branches from PRs or otherwise.

name: Preview Builds

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:
    inputs:
      baseBranch:
        description: Base Branch
        required: true
      installableBranch:
        description: Installable Branch
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ## Pushes to main or manually dispatched experimental previews
  branch:
    if: github.repository == 'remix-run/remix' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.baseBranch || 'main' }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup git
        run: |
          git config --local user.email "hello@remix.run"
          git config --local user.name "Remix Run Bot"

      - name: Build installable branch
        run: pnpm run setup-installable-branch ${{ inputs.installableBranch || 'preview' }}

      ## Force push over the preview branch
      - name: Push changes (preview)
        if: github.event_name == 'push'
        run: |
          git push --force --set-upstream origin preview
          echo "ðŸ’¿ pushed installable branch: https://github.com/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)"

      ## Don't force push for experimental releases in case of a branch name collision
      - name: Push changes (experimental)
        if: github.event_name == 'workflow_dispatch'
        run: |
          git push --set-upstream origin ${{ inputs.installableBranch  }}
          echo "ðŸ’¿ pushed installable branch: https://github.com/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)"

  ## Pull Request Handling
  pr-preview:
    if: github.repository == 'remix-run/remix' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build previews when PR's are open
      - name: Build preview branch
        if: github.event.pull_request.state == 'open'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config --local user.email "hello@remix.run"
          git config --local user.name "Remix Run Bot"

          PREVIEW_BRANCH_NAME="preview/${{ github.event.pull_request.number }}"
          pnpm run setup-installable-branch $PREVIEW_BRANCH_NAME

          git push --force --set-upstream origin $PREVIEW_BRANCH_NAME
          echo "pushed installable branch: https://github.com/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)"

          pnpm run pr-preview comment ${{ github.event.pull_request.number }} $PREVIEW_BRANCH_NAME

      # Cleanup previews when PR's are closed
      - name: Cleanup preview branch
        if: github.event.pull_request.state == 'closed'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          PREVIEW_BRANCH_NAME="preview/${{ github.event.pull_request.number }}"
          pnpm run pr-preview cleanup ${{ github.event.pull_request.number }} $PREVIEW_BRANCH_NAME
