name: release

on:
  release:
    types: [published]
  schedule:
    - cron: "0 7 * * *" # every day at 12AM PST

jobs:
  nightly:
    name: ðŸŒ’ Nightly Release
    if: |
      github.repository == 'remix-run/remix' &&
      github.event.action == 'published' &&
      github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: dev
          token: ${{ secrets.NIGHTLY_PAT }}
          fetch-depth: 0

      - name: âŽ” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"

      - name: ðŸ“¥ Install deps
        # even though this is called "npm-install" it does use yarn to install
        # because we have a yarn.lock and caches efficiently.
        uses: bahmutov/npm-install@v1

      - name: ðŸ— Build
        run: yarn build

      - name: â¤´ï¸ Update Version
        id: version
        run: |
          SHA=$(git rev-parse HEAD)
          SHORT_SHA=${SHA::7}
          NEXT_VERSION=0.0.0-nightly-${SHORT_SHA}
          echo ::set-output name=NEXT_VERSION::${NEXT_VERSION}

          git checkout -b nightly/${NEXT_VERSION}
          npm version ${NEXT_VERSION}

          git push origin --tags

      - name: ðŸ” Setup npm auth
        run: |
          echo "registry=https://registry.npmjs.org" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: ðŸš€ Publish
        run: npm run publish

      - name: ðŸ± Create GitHub release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: true
          release_name: v${{ steps.version.outputs.NEXT_VERSION }}
          tag_name: v${{ steps.version.outputs.NEXT_VERSION }}
        env:
          # need this token in order to have it trigger the comment workflow
          GITHUB_TOKEN: ${{ secrets.NIGHTLY_PAT }}

  manual:
    name: ðŸ“ Manual Release
    if: |
      github.repository == 'remix-run/remix' &&
      github.event.action == 'published' &&
      github.event_name != 'schedule' &&
      !github.event.release.prerelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"

      - run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache

      - name: Restore dependency cache
        uses: actions/cache@v2
        with:
          path: "${{ steps.yarn-cache.outputs.dir }}"
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Setup npm auth
        run: |
          echo "registry=https://registry.npmjs.org" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Publish
        run: npm run publish

  arc_deploy:
    name: Architect Deploy
    needs: [manual]
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: ./scripts/deployment-test

      - name: Install latest version of npm
        run: npm install -g npm@latest
        working-directory: ./scripts/deployment-test

      - name: Deploy to Arc
        run: node ./arc.mjs
        working-directory: ./scripts/deployment-test
        env:
          CI: true
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}

  cf_pages_deploy:
    name: "CF Pages Deploy"
    needs: [manual]
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: ./scripts/deployment-test

      - name: Install latest version of npm
        run: npm install -g npm@latest
        working-directory: ./scripts/deployment-test

      - name: Deploy to Cloudflare Pages
        run: node ./cf-pages.mjs
        working-directory: ./scripts/deployment-test
        env:
          CF_ACCOUNT_ID: ${{ secrets.TEST_CF_ACCOUNT_ID }}
          CF_GLOBAL_API_KEY: ${{ secrets.TEST_CF_GLOBAL_API_KEY }}
          CF_EMAIL: ${{ secrets.TEST_CF_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.TEST_CF_GITHUB_TOKEN }}

  cf_workers_deploy:
    name: "CF Workers Deploy"
    needs: [manual]
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: ./scripts/deployment-test

      - name: Install latest version of npm
        run: npm install -g npm@latest
        working-directory: ./scripts/deployment-test

      - name: Deploy to Cloudflare Workers
        run: node ./cf-workers.mjs
        working-directory: ./scripts/deployment-test
        env:
          CF_ACCOUNT_ID: ${{ secrets.TEST_CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.TEST_CF_API_TOKEN }}

  fly_deploy:
    name: "Fly Deploy"
    needs: [manual]
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: ./scripts/deployment-test

      - name: Install latest version of npm
        run: npm install -g npm@latest
        working-directory: ./scripts/deployment-test

      - name: Install the Fly CLI
        run: curl -L https://fly.io/install.sh | FLYCTL_INSTALL=/usr/local sh

      - name: Deploy to Fly
        run: node ./fly.mjs
        working-directory: ./scripts/deployment-test
        env:
          FLY_API_TOKEN: ${{ secrets.TEST_FLY_TOKEN }}

  netlify_deploy:
    name: "Netlify Deploy"
    needs: [manual]
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: ./scripts/deployment-test

      - name: Install latest version of npm
        run: npm install -g npm@latest
        working-directory: ./scripts/deployment-test

      - name: Deploy to Netlify
        run: node ./netlify.mjs
        working-directory: ./scripts/deployment-test
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.TEST_NETLIFY_TOKEN }}

  vercel_deploy:
    name: "Vercel Deploy"
    needs: [manual]
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "::set-output name=version::$(cat .nvmrc)"
        id: nvmrc

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvmrc.outputs.version }}"
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: ./scripts/deployment-test

      - name: Install latest version of npm
        run: npm install -g npm@latest
        working-directory: ./scripts/deployment-test

      - name: Deploy to Vercel
        run: node ./vercel.mjs
        working-directory: ./scripts/deployment-test
        env:
          VERCEL_TOKEN: ${{ secrets.TEST_VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.TEST_VERCEL_USER_ID }}
