name: ğŸ¥ Remix Stacks Test

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  setup:
    name: Remix Stacks Test
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack:
          - repo: "remix-run/indie-stack"
            name: "indie"
          - repo: "remix-run/blues-stack"
            name: "blues"
          - repo: "remix-run/grunge-stack"
            name: "grunge"
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.1

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: âš’ï¸ Create new ${{ matrix.stack.name }} app with ${{ inputs.version }}
        run: |
          npx -y create-remix@${{ inputs.version }} ${{ matrix.stack.name }} --template ${{ matrix.stack.repo }} --typescript --no-install

      - name: â” Setup dependency caching
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: ${{ matrix.stack.name }}/package.json

      - name: ğŸ“¥ Install deps
        run: npm install
        working-directory: ${{ matrix.stack.name }}

      - name: Run `remix init`
        run: |
          cd ${{ matrix.stack.name }}
          npx remix init

      - name: ğŸ„ Copy test env vars
        run: |
          cd ${{ matrix.stack.name }}
          cp .env.example .env

      - name: ğŸ“ Zip artifact
        run: zip ${{ matrix.stack.name }}.zip ./${{ matrix.stack.name }} -r -x "**/node_modules/*"

      - name: ğŸ—„ï¸ Archive ${{ matrix.stack.name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.stack.name }}-archive
          path: ${{ matrix.stack.name }}.zip

  lint:
    name: â¬£ ESLint
    if: github.repository == 'remix-run/remix'
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack:
          - repo: "remix-run/indie-stack"
            name: "indie"
          - repo: "remix-run/blues-stack"
            name: "blues"
          - repo: "remix-run/grunge-stack"
            name: "grunge"
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.1

      - name: ğŸ—„ï¸ Restore ${{ matrix.stack.name }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.stack.name }}-archive

      - name: ğŸ“ Unzip artifact
        run: unzip ${{ matrix.stack.name }}.zip

      - name: â” Setup node and dependency caching
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ${{ matrix.stack.name }}/package.json

      - name: ğŸ“¥ Install deps
        run: npm install
        working-directory: ${{ matrix.stack.name }}

      - name: ğŸ”¬ Lint
        run: |
          cd ${{ matrix.stack.name }}
          npm run lint

  typecheck:
    name: Ê¦ TypeScript
    needs: [setup]
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack:
          - repo: "remix-run/indie-stack"
            name: "indie"
          - repo: "remix-run/blues-stack"
            name: "blues"
          - repo: "remix-run/grunge-stack"
            name: "grunge"
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.1

      - name: ğŸ—„ï¸ Restore ${{ matrix.stack.name }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.stack.name }}-archive

      - name: ğŸ“ Unzip artifact
        run: unzip ${{ matrix.stack.name }}.zip

      - name: â” Setup node and dependency caching
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ${{ matrix.stack.name }}/package.json

      - name: ğŸ“¥ Install deps
        run: npm install
        working-directory: ${{ matrix.stack.name }}

      - name: ğŸ” Type check
        run: |
          cd ${{ matrix.stack.name }}
          npm run typecheck --if-present

  vitest:
    name: âš¡ Vitest
    if: github.repository == 'remix-run/remix'
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack:
          - repo: "remix-run/indie-stack"
            name: "indie"
          - repo: "remix-run/blues-stack"
            name: "blues"
          - repo: "remix-run/grunge-stack"
            name: "grunge"
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.1

      - name: ğŸ—„ï¸ Restore ${{ matrix.stack.name }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.stack.name }}-archive

      - name: ğŸ“ Unzip artifact
        run: unzip ${{ matrix.stack.name }}.zip

      - name: â” Setup node and dependency caching
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ${{ matrix.stack.name }}/package.json

      - name: ğŸ“¥ Install deps
        run: npm install
        working-directory: ${{ matrix.stack.name }}

      - name: âš¡ Run vitest
        run: |
          cd ${{ matrix.stack.name }}
          npm run test -- --coverage

  cypress:
    name: âš«ï¸ Cypress
    if: github.repository == 'remix-run/remix'
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack:
          - repo: "remix-run/indie-stack"
            name: "indie"
            cypress: "npm run start:mocks"
          - repo: "remix-run/blues-stack"
            name: "blues"
            cypress: "npm run start:mocks"
          - repo: "remix-run/grunge-stack"
            name: "grunge"
            cypress: "npm run dev"
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.1

      - name: ğŸ—„ï¸ Restore ${{ matrix.stack.name }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.stack.name }}-archive

      - name: ğŸ“ Unzip artifact
        run: unzip ${{ matrix.stack.name }}.zip

      - name: â” Setup node and dependency caching
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ${{ matrix.stack.name }}/package.json

      - name: ğŸ“¥ Install deps
        run: npm install
        working-directory: ${{ matrix.stack.name }}

      - name: ğŸ³ Docker compose
        if: ${{ matrix.stack.name == 'blues' }}
        # the sleep is just there to give time for postgres to get started
        run: |
          cd ${{ matrix.stack.name }}
          docker-compose up -d && sleep 3
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"

      - name: ğŸ›  Setup Database
        if: ${{ matrix.stack.name != 'grunge' }}
        run: |
          cd ${{ matrix.stack.name }}
          npx prisma migrate reset --force

      - name: âš™ï¸ Build
        run: |
          cd ${{ matrix.stack.name }}
          npm run build

      - name: ğŸŒ³ Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: ${{ matrix.stack.cypress }}
          wait-on: "http://localhost:8811"
          working-directory: ${{ matrix.stack.name }}
        env:
          PORT: "8811"
