name: PR (Full)

# PRs touching create-remix/remix-dev will also run on Windows and OSX

on:
  pull_request:
    paths:
      - "packages/create-remix/**"
      - "packages/remix-dev/**"
      - "!**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-windows:
    name: "ðŸ§ª Unit Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-unit.yml
    with:
      os: "windows-latest"
      node_version: '["20.5.1"]'

  integration-firefox:
    name: "ðŸ‘€ Integration Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-integration.yml
    with:
      os: "ubuntu-latest"
      node_version: '["20.5.1"]'
      browser: '["firefox"]'

  integration-msedge:
    name: "ðŸ‘€ Integration Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-integration.yml
    with:
      os: "windows-latest"
      node_version: '["20.5.1"]'
      browser: '["msedge"]'

  integration-webkit:
    name: "ðŸ‘€ Integration Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-integration.yml
    with:
      os: "macos-latest"
      node_version: '["20.5.1"]'
      browser: '["webkit"]'
