name: Branch

# main/dev/release-* branches and nightly tags will get the full run across
# all OS/browsers for multiple node versions

on:
  push:
    branches:
      - v2
      - release-v2
    paths-ignore:
      - "docs/**"
      - "scripts/**"
      - "contributors.yml"
      - "**/*.md"

jobs:
  build:
    name: "âš™ï¸ Build"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-build.yml

  unit-ubuntu:
    name: "ğŸ§ª Unit Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-unit.yml
    with:
      os: "ubuntu-latest"
      node_version: "[18, 20]"

  unit-windows:
    name: "ğŸ§ª Unit Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-unit.yml
    with:
      os: "windows-latest"
      node_version: "[18, 20]"

  integration-ubuntu:
    name: "ğŸ‘€ Integration Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-integration.yml
    with:
      os: "ubuntu-latest"
      node_version: "[18, 20]"
      browser: '["chromium", "firefox"]'

  integration-windows:
    name: "ğŸ‘€ Integration Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-integration.yml
    with:
      os: "windows-latest"
      node_version: "[18, 20]"
      browser: '["msedge"]'

  integration-macos:
    name: "ğŸ‘€ Integration Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-integration.yml
    with:
      os: "macos-latest"
      node_version: "[18, 20]"
      browser: '["webkit"]'
