name: PR (Base)

# All PRs touching code will run tests on ubuntu/node/chromium

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "templates/**"
      - "scripts/**"
      - "contributors.yml"
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "âš™ï¸ Build"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-build.yml

  unit-ubuntu:
    name: "ğŸ§ª Unit Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-unit.yml
    with:
      os: "ubuntu-latest"
      node_version: "[20]"

  integration-chromium:
    name: "ğŸ‘€ Integration Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-integration.yml
    with:
      os: "ubuntu-latest"
      node_version: "[20]"
      browser: '["chromium"]'
