name: Branch

# main/dev branches will get the full run across all OS/browsers

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "docs/**"
      - "scripts/**"
      - "contributors.yml"
      - "**/*.md"

jobs:
  build:
    name: "âš™ï¸ Build"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-build.yml

  unit-ubuntu:
    name: "ğŸ§ª Unit Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-unit.yml
    with:
      os: "ubuntu-latest"
      node_version: '["latest"]'

  unit-windows:
    name: "ğŸ§ª Unit Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-unit.yml
    with:
      os: "windows-latest"
      node_version: '["latest"]'

  integration-ubuntu:
    name: "ğŸ‘€ Integration Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-integration.yml
    with:
      os: "ubuntu-latest"
      node_version: '["latest"]'
      browser: '["chromium", "firefox"]'

  integration-windows:
    name: "ğŸ‘€ Integration Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-integration.yml
    with:
      os: "windows-latest"
      node_version: '["latest"]'
      browser: '["msedge"]'

  integration-macos:
    name: "ğŸ‘€ Integration Test"
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/shared-test-integration.yml
    with:
      os: "macos-latest"
      node_version: '["latest"]'
      browser: '["webkit"]'
